gospelcenter_simple_homepage:
    defaults: { _controller: gospelcenterSimpleBundle:Default:index }
    host: "gospel-center.org"


gospelcenter_simple_cote:
    defaults: { _controller: gospelcenterSimpleBundle:Default:cote }
    host: "gc-lacote.org"

gospelcenter_simple_beroche:
    defaults: { _controller: gospelcenterSimpleBundle:Default:beroche }
    host: "gc-beroche.org"

gospelcenter_simple_fribourg:
    defaults: { _controller: gospelcenterSimpleBundle:Default:fribourg }
    host: "gc-fribourg.org"